"use client";
import { useEffect, useState } from "react";
import Editor from "@monaco-editor/react";
import { useParams } from "next/navigation";
import { authClient } from "../../auth-client";
import { Shell } from "../../components";
import { problems } from "../../data";
const templates: Record<string,string>={cpp:"#include <bits/stdc++.h>\nusing namespace std;\n\nint main() {\n  return 0;\n}",python:"def solve():\n    pass\n\nif __name__ == '__main__':\n    solve()",javascript:"const fs = require('fs');\nconst input = fs.readFileSync(0, 'utf8').trim();\n\nfunction solve() {\n}\n\nsolve();"};
export default function Match(){const {id}=useParams<{id:string}>();const {data:session}=authClient.useSession();const [status,setStatus]=useState("Ready");const [language,setLanguage]=useState("cpp");const [code,setCode]=useState(templates.cpp);const [seconds,setSeconds]=useState(0);const problem=problems[3];useEffect(()=>{if(!session){setSeconds(0);return}const timer=setInterval(()=>setSeconds(value=>value+1),1000);return()=>clearInterval(timer)},[session]);const time=`${String(Math.floor(seconds/60)).padStart(2,"0")}:${String(seconds%60).padStart(2,"0")}`;return <Shell><main className="match-page"><header><div><p className="eyebrow">MATCH #{id.slice(0,8).toUpperCase()}</p><h1>{problem.title}</h1></div><div className="match-timer"><small>TIME ELAPSED</small><b>{time}</b></div><div className="opponent"><span className="avatar lime">MN</span><div><small>OPPONENT</small><b>mira_nova · <em>{status}</em></b></div></div></header><div className="match-grid"><article className="match-statement"><p>{problem.description}</p><h2>Constraints</h2><p>{problem.constraints}</p><h2>Sample</h2><pre>{problem.sampleInput}</pre></article><section className="editor-panel"><div className="editor-tools"><select value={language} onChange={event=>{setLanguage(event.target.value);setCode(templates[event.target.value]);setStatus("Ready")}}><option value="cpp">C++17</option><option value="python">Python 3</option><option value="javascript">JavaScript</option></select><span>{status}</span></div><Editor height="420px" theme="vs-dark" language={language} value={code} onChange={value=>setCode(value||"")} options={{minimap:{enabled:false},fontSize:14,padding:{top:16}}}/><div className="editor-actions"><button onClick={()=>setStatus("Running")} disabled={!session}>Run code</button><button className="button" onClick={()=>setStatus("Accepted")} disabled={!session}>Submit <span>→</span></button>{!session&&<small>Sign in to run or submit.</small>}</div></section></div></main></Shell>}
